### ISSUE TITLE
当多个合约存在同名函数时，contractMapsInfo构建methodIdMap会有问题

### ISSUE THREAD

**Issue by xiaomdong** [WeBankFinTech/WeBASE-Collect-Bee#20]
contractMapsInfo构建methodIdMap 采用ABI中函数methodId作为key，value为对应的函数。
当多个合约存在同名函数时，同名函数的methodId是相同的，导致methodIdMap后构建出错。

**Comment by dalaocu** [comment]
> contractMapsInfo构建methodIdMap 采用ABI中函数methodId作为key，value为对应的函数。
> 当多个合约存在同名函数时，同名函数的methodId是相同的，导致methodIdMap后构建出错。

已修复并合入。
